# Generated by Django 3.2.5 on 2021-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
