# Generated by Django 3.2.5 on 2021-07-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sow',
            old_name='name',
            new_name='months',
        ),
    ]
