# Generated by Django 3.2.5 on 2021-07-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0002_rename_name_sow_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sow',
            old_name='months',
            new_name='month',
        ),
    ]
