# Generated by Django 3.2.5 on 2021-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0002_alter_sow_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='month',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
