# Generated by Django 3.2.5 on 2021-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='sow',
            field=models.ManyToManyField(related_name='sows', to='sows.Sow'),
        ),
    ]
