# Generated by Django 3.2.5 on 2021-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='instructors',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
