# Generated by Django 3.2.5 on 2021-07-23 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0002_crop_sow'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
