# Generated by Django 3.2.5 on 2021-07-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_instructors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='instructors',
            new_name='instructions',
        ),
    ]
