# Generated by Django 3.2.5 on 2021-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
