# Generated by Django 3.2.5 on 2021-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_crop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='instructions',
            field=models.JSONField(null=True),
        ),
    ]
