# Generated by Django 3.2.5 on 2021-07-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
