# Generated by Django 3.2.5 on 2021-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='inside_plant',
            field=models.BooleanField(default=False),
        ),
    ]
