# Generated by Django 3.2.5 on 2021-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0002_alter_sow_month'),
        ('crops', '0004_alter_crop_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='sow',
            field=models.ManyToManyField(null=True, related_name='sows', to='sows.Sow'),
        ),
    ]
