# Generated by Django 3.2.5 on 2021-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0003_alter_sow_month'),
        ('crops', '0005_alter_crop_sow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='sow',
            field=models.ManyToManyField(related_name='sows', to='sows.Sow'),
        ),
    ]
